/*
** EPITECH PROJECT, 2018
** strace
** File description:
** syscalls.h
*/

#ifndef SYSCALL_TAB_H_
# define SYSCALL_TAB_H_

# include "strace.h"

typedef int (*print_special)(strace_t *, unsigned long *);
typedef int (*print_value)(strace_t *, unsigned long);

typedef enum {
	VOID = 0,
	INT = 1,
	UINT = 2,
	LONG = 3,
	ULONG = 4,
	PTR = 5,
	STR = 6,
	MAX_TYPE = 7
} type_t;

typedef struct syscall_s {
	const char *name;
	type_t ret;
	char n_args;
	type_t args[6];
	print_special print_f;
} syscall_t;

typedef struct function_ptr_s {
	type_t type;
	print_value func;
} function_ptr_t;

int print_fstat(strace_t *info, unsigned long *regs);
int print_read(strace_t *info, unsigned long *regs);
int print_nanosleep(strace_t *info, unsigned long *regs);
int print_int(strace_t *info, unsigned long reg);
int print_uint(strace_t *info, unsigned long reg);
int print_long(strace_t *info, unsigned long reg);
int print_ulong(strace_t *info, unsigned long reg);
int print_ptr(strace_t *info, unsigned long reg);
int print_str(strace_t *info, unsigned long reg);
int print_hex(strace_t *info, unsigned long reg);
int rough_print(strace_t *info, unsigned long *regs);

static const function_ptr_t print_ptr_g[] = {
	{ VOID, 0 },
	{ INT, &print_int },
	{ UINT, &print_uint },
	{ LONG, &print_long },
	{ ULONG, &print_ulong },
	{ PTR, &print_ptr },
	{ STR, &print_str },
};

static const syscall_t syscall_tab_g[] = {
	{ "read", LONG, 3, { INT, STR, ULONG }, &print_read },
	{ "write", LONG, 3, { INT, STR, ULONG }, 0 },
	{ "open", INT, 3, { STR, INT, INT }, 0 },
	{ "close", INT, 1, { INT }, 0 },
	{ "stat", INT, 2, { STR, PTR }, 0 },
	{ "fstat", INT, 2, { INT, PTR }, &print_fstat },
	{ "lstat", INT, 2, { STR, PTR }, 0 },
	{ "poll", INT, 3, { PTR, INT, INT }, 0 },
	{ "lseek", LONG, 3, { INT, LONG, INT }, 0 },
	{ "mmap", PTR, 6, { INT, INT, INT, INT, INT, LONG }, 0 },
	{ "mprotect", INT, 3, { INT, ULONG, INT }, 0 },
	{ "munmap", INT, 2, { INT, ULONG }, 0 },
	{ "brk", PTR, 1, { PTR }, 0 },
	{ "rt_sigaction", INT, 4, { INT, PTR, PTR, INT }, 0 },
	{ "rt_sigprocmask", INT, 4, { INT, PTR, PTR, INT }, 0 },
	{ "rt_sigreturn", INT, 0, { VOID }, 0 },
	{ "ioctl", INT, 3, { INT, INT, INT }, 0 },
	{ "pread64", LONG, 4, { INT, STR, ULONG, LONG }, 0 },
	{ "pwrite64", LONG, 4, { INT, STR, ULONG, LONG }, 0 },
	{ "readv", LONG, 3, { INT, PTR, INT }, 0 },
	{ "writev", LONG, 3, { INT, PTR, INT }, 0 },
	{ "access", INT, 2, { STR, INT }, 0 },
	{ "pipe", INT, 1, { PTR }, 0 },
	{ "select", INT, 5, { INT, PTR, PTR, PTR, PTR }, 0 },
	{ "sched_yield", INT, 0, { VOID }, 0 },
	{ "mremap", PTR, 4, { PTR, ULONG, ULONG, INT }, 0 },
	{ "msync", INT, 3, { INT, INT, INT }, 0 },
	{ "mincore", INT, 3, { INT, INT, STR }, 0 },
	{ "madvise", INT, 3, { INT, INT, INT }, 0 },
	{ "shmget", INT, 3, { INT, INT, INT }, 0 },
	{ "shmat", PTR, 3, { INT, STR, INT }, 0 },
	{ "shmctl", INT, 3, { INT, INT, PTR }, 0 },
	{ "dup", INT, 1, { INT }, 0 },
	{ "dup2", INT, 2, { INT, INT }, 0 },
	{ "pause", INT, 0, { VOID }, 0 },
	{ "nanosleep", INT, 2, { PTR, PTR }, &print_nanosleep },
	{ "getitimer", INT, 2, { INT, PTR }, 0 },
	{ "alarm", UINT, 1, { UINT }, 0 },
	{ "setitimer", INT, 3, { INT, PTR, PTR }, 0 },
	{ "getpid", INT, 0, { VOID }, 0 },
	{ "sendfile", LONG, 4, { INT, INT, PTR, LONG }, 0 },
	{ "socket", INT, 3, { INT, INT, INT }, 0 },
	{ "connect", INT, 3, { INT, PTR, INT }, 0 },
	{ "accept", INT, 3, { INT, PTR, PTR }, 0 },
	{ "sendto", LONG, 6, { INT, PTR, ULONG, INT, PTR, INT }, 0 },
	{ "recvfrom", LONG, 6, { INT, PTR, ULONG, INT, PTR, PTR }, 0 },
	{ "sendmsg", LONG, 3, { INT, PTR, INT }, 0 },
	{ "recvmsg", LONG, 3, { INT, PTR, INT }, 0 },
	{ "shutdown", INT, 2, { INT, INT }, 0 },
	{ "bind", INT, 3, { INT, PTR, LONG }, 0 },
	{ "listen", INT, 2, { INT, INT }, 0 },
	{ "getsockname", INT, 3, { INT, PTR, PTR }, 0 },
	{ "getpeername", INT, 3, { INT, PTR, PTR }, 0 },
	{ "socketpair", INT, 4, { INT, INT, INT, PTR }, 0 },
	{ "setsockopt", INT, 5, { INT, INT, INT, STR, LONG }, 0 },
	{ "getsockopt", INT, 5, { INT, INT, INT, STR, PTR }, 0 },
	{ "clone", INT, 5, { INT, INT, PTR, PTR, INT }, 0 },
	{ "fork", INT, 0, { VOID }, 0 },
	{ "vfork", INT, 0, { VOID }, 0 },
	{ "execve", INT, 3, { STR, PTR, PTR }, 0 },
	{ "exit", VOID, 1, { INT }, 0 },
	{ "wait4", INT, 4, { INT, PTR, INT, PTR }, 0 },
	{ "kill", INT, 2, { INT, INT }, 0 },
	{ "uname", INT, 1, { PTR }, 0 },
	{ "semget", INT, 3, { INT, INT, INT }, 0 },
	{ "semop", INT, 3, { INT, PTR, INT }, 0 },
	{ "semctl", INT, 4, { INT, INT, INT, INT }, 0 },
	{ "shmdt", INT, 1, { STR }, 0 },
	{ "msgget", INT, 2, { INT, INT }, 0 },
	{ "msgsnd", INT, 4, { INT, PTR, INT, INT }, 0 },
	{ "msgrcv", INT, 5, { INT, PTR, INT, LONG, INT }, 0 },
	{ "msgctl", INT, 3, { INT, INT, PTR }, 0 },
	{ "fcntl", INT, 3, { INT, INT, INT }, 0 },
	{ "flock", INT, 2, { INT, INT }, 0 },
	{ "fsync", INT, 1, { INT }, 0 },
	{ "fdatasync", INT, 1, { INT }, 0 },
	{ "truncate", INT, 2, { STR, LONG }, 0 },
	{ "ftruncate", INT, 2, { INT, LONG }, 0 },
	{ "getdents", INT, 3, { UINT, PTR, UINT }, 0 },
	{ "getcwd", LONG, 2, { STR, ULONG }, 0 },
	{ "chdir", INT, 1, { STR }, 0 },
	{ "fchdir", INT, 1, { INT }, 0 },
	{ "rename", INT, 2, { STR, STR }, 0 },
	{ "mkdir", INT, 2, { STR, INT }, 0 },
	{ "rmdir", INT, 1, { STR }, 0 },
	{ "creat", INT, 2, { STR, INT }, 0 },
	{ "link", INT, 2, { STR, STR }, 0 },
	{ "unlink", INT, 1, { STR }, 0 },
	{ "symlink", INT, 2, { STR, STR }, 0 },
	{ "readlink", LONG, 3, { STR, STR, ULONG }, 0 },
	{ "chmod", INT, 2, { STR, INT }, 0 },
	{ "fchmod", INT, 2, { INT, INT }, 0 },
	{ "chown", INT, 3, { STR, INT, INT }, 0 },
	{ "fchown", INT, 3, { INT, INT, INT }, 0 },
	{ "lchown", INT, 3, { STR, INT, INT }, 0 },
	{ "umask", INT, 1, { INT }, 0 },
	{ "gettimeofday", INT, 2, { PTR, PTR }, 0 },
	{ "getrlimit", INT, 2, { INT, PTR }, 0 },
	{ "getrusage", INT, 2, { INT, PTR }, 0 },
	{ "sysinfo", INT, 1, { PTR }, 0 },
	{ "times", INT, 1, { PTR }, 0 },
	{ "ptrace", LONG, 4, { INT, INT, INT, INT }, 0 },
	{ "getuid", INT, 0, { VOID }, 0 },
	{ "syslog", INT, 3, { INT, STR, INT }, 0 },
	{ "getgid", INT, 0, { VOID }, 0 },
	{ "setuid", INT, 1, { INT }, 0 },
	{ "setgid", INT, 1, { INT }, 0 },
	{ "geteuid", INT, 0, { VOID }, 0 },
	{ "getegid", INT, 0, { VOID }, 0 },
	{ "setpgid", INT, 2, { INT, INT }, 0 },
	{ "getppid", INT, 0, { VOID }, 0 },
	{ "getpgrp", INT, 0, { VOID }, 0 },
	{ "setsid", INT, 0, { VOID }, 0 },
	{ "setreuid", INT, 2, { INT, INT }, 0 },
	{ "setregid", INT, 2, { INT, INT }, 0 },
	{ "getgroups", INT, 2, { INT, PTR }, 0 },
	{ "setgroups", INT, 2, { ULONG, PTR }, 0 },
	{ "setresuid", INT, 3, { INT, INT, INT }, 0 },
	{ "getresuid", INT, 3, { PTR, PTR, PTR }, 0 },
	{ "setresgid", INT, 3, { INT, INT, INT }, 0 },
	{ "getresgid", INT, 3, { PTR, PTR, PTR }, 0 },
	{ "getpgid", INT, 1, { INT }, 0 },
	{ "setfsuid", INT, 1, { INT }, 0 },
	{ "setfsgid", INT, 1, { INT }, 0 },
	{ "getsid", INT, 1, { INT }, 0 },
	{ "capget", INT, 2, { PTR, PTR }, 0 },
	{ "capset", INT, 2, { PTR, PTR }, 0 },
	{ "rt_sigpending", INT, 2, { PTR, INT }, 0 },
	{ "rt_sigtimedwait", INT, 4, { PTR, PTR, PTR, INT }, 0 },
	{ "rt_sigqueueinfo", LONG, 3, { INT, INT, PTR }, 0 },
	{ "rt_sigsuspend", INT, 2, { PTR, INT }, 0 },
	{ "sigaltstack", INT, 2, { PTR, PTR }, 0 },
	{ "utime", INT, 2, { STR, PTR }, 0 },
	{ "mknod", INT, 3, { STR, INT, INT }, 0 },
	{ "uselib", INT, 1, { STR }, 0 },
	{ "personality", INT, 1, { ULONG }, 0 },
	{ "ustat", INT, 2, { INT, PTR }, 0 },
	{ "statfs", INT, 2, { STR, PTR }, 0 },
	{ "fstatfs", INT, 2, { INT, PTR }, 0 },
	{ "sysfs", INT, 3, { INT, INT, INT }, 0 },
	{ "getpriority", INT, 2, { INT, INT }, 0 },
	{ "setpriority", INT, 3, { INT, INT, INT }, 0 },
	{ "sched_setparam", INT, 2, { INT, PTR }, 0 },
	{ "sched_getparam", INT, 2, { INT, PTR }, 0 },
	{ "sched_setscheduler", INT, 3, { INT, INT, PTR }, 0 },
	{ "sched_getscheduler", INT, 1, { INT }, 0 },
	{ "sched_get_priority_max", INT, 1, { INT }, 0 },
	{ "sched_get_priority_min", INT, 1, { INT }, 0 },
	{ "sched_rr_get_interval", INT, 2, { INT, PTR }, 0 },
	{ "mlock", INT, 2, { INT, ULONG }, 0 },
	{ "munlock", INT, 2, { INT, ULONG }, 0 },
	{ "mlockall", INT, 1, { INT }, 0 },
	{ "munlockall", INT, 0, { VOID }, 0 },
	{ "vhangup", INT, 0, { VOID }, 0 },
	{ "modify_ldt", INT, 3, { INT, PTR, ULONG }, 0 },
	{ "pivot_root", INT, 2, { STR, STR }, 0 },
	{ "_sysctl", INT, 1, { PTR }, 0 },
	{ "prctl", INT, 5, { INT, ULONG, ULONG, ULONG, ULONG }, 0 },
	{ "arch_prctl", INT, 3, { PTR, INT, PTR }, 0 },
	{ "adjtimex", INT, 1, { PTR }, 0 },
	{ "setrlimit", INT, 2, { INT, PTR }, 0 },
	{ "chroot", INT, 1, { STR }, 0 },
	{ "sync", VOID, 0, { VOID }, 0 },
	{ "acct", INT, 1, { STR }, 0 },
	{ "settimeofday", INT, 2, { PTR, PTR }, 0 },
	{ "mount", INT, 5, { STR, STR, STR, ULONG, PTR }, 0 },
	{ "umount2", INT, 2, { STR, INT }, 0 },
	{ "swapon", INT, 2, { STR, INT }, 0 },
	{ "swapoff", INT, 1, { STR }, 0 },
	{ "reboot", INT, 4, { INT, INT, INT, PTR }, 0 },
	{ "sethostname", INT, 2, { STR, ULONG }, 0 },
	{ "setdomainname", INT, 2, { STR, ULONG }, 0 },
	{ "iopl", INT, 1, { INT }, 0 },
	{ "ioperm", INT, 3, { ULONG, ULONG, INT }, 0 },
	{ "create_module", INT, 0, { VOID }, 0 },
	{ "init_module", INT, 3, { PTR, ULONG, STR }, 0 },
	{ "delete_module", INT, 2, { STR, INT }, 0 },
	{ "get_kernel_syms", INT, 0, { VOID }, 0 },
	{ "query_module", INT, 0, { VOID }, 0 },
	{ "quotactl", INT, 4, { INT, STR, INT, PTR }, 0 },
	{ "nfsservctl", INT, 0, { VOID }, 0 },
	{ "getpmsg", INT, 0, { VOID }, 0 },
	{ "putpmsg", INT, 0, { VOID }, 0 },
	{ "afs_syscall", INT, 0, { VOID }, 0 },
	{ "tuxcall", INT, 0, { VOID }, 0 },
	{ "security", INT, 0, { VOID }, 0 },
	{ "gettid", INT, 0, { VOID }, 0 },
	{ "readahead", LONG, 3, { INT, ULONG, ULONG }, 0 },
	{ "setxattr", INT, 5, { STR, STR, PTR, ULONG, INT }, 0 },
	{ "lsetxattr", INT, 5, { STR, STR, PTR, ULONG, INT }, 0 },
	{ "fsetxattr", INT, 5, { INT, STR, PTR, ULONG, INT }, 0 },
	{ "getxattr", LONG, 4, { STR, STR, PTR, ULONG }, 0 },
	{ "lgetxattr", LONG, 4, { STR, STR, PTR, ULONG }, 0 },
	{ "fgetxattr", LONG, 4, { INT, STR, PTR, ULONG }, 0 },
	{ "listxattr", LONG, 3, { STR, STR, ULONG }, 0 },
	{ "llistxattr", LONG, 3, { STR, STR, ULONG }, 0 },
	{ "flistxattr", LONG, 3, { INT, STR, ULONG }, 0 },
	{ "removexattr", INT, 2, { STR, STR }, 0 },
	{ "lremovexattr", INT, 2, { STR, STR }, 0 },
	{ "fremovexattr", INT, 2, { INT, STR }, 0 },
	{ "tkill", INT, 2, { INT, INT }, 0 },
	{ "time", INT, 1, { PTR }, 0 },
	{ "futex", INT, 6, { PTR, INT, INT, PTR, PTR, INT }, 0 },
	{ "sched_setaffinity", INT, 3, { INT, INT, PTR }, 0 },
	{ "sched_getaffinity", INT, 3, { INT, INT, PTR }, 0 },
	{ "set_thread_area", INT, 1, { PTR }, 0 },
	{ "io_setup", INT, 2, { UINT, PTR }, 0 },
	{ "io_destroy", INT, 1, { INT }, 0 },
	{ "io_getevents", INT, 5, { INT, INT, INT, PTR, PTR }, 0 },
	{ "io_submit", INT, 3, { INT, INT, PTR }, 0 },
	{ "io_cancel", INT, 3, { INT, PTR, PTR }, 0 },
	{ "get_thread_area", INT, 1, { PTR }, 0 },
	{ "lookup_dcookie", INT, 3, { INT, STR, INT }, 0 },
	{ "epoll_create", INT, 1, { INT }, 0 },
	{ "epoll_ctl_old", INT, 0, { VOID }, 0 },
	{ "epoll_wait_old", INT, 0, { VOID }, 0 },
	{ "remap_file_pages", INT, 5, { INT, ULONG, INT, LONG, INT }, 0 },
	{ "getdents64", INT, 3, { UINT, PTR, UINT }, 0 },
	{ "set_tid_address", LONG, 1, { PTR }, 0 },
	{ "restart_syscall", INT, 0, { VOID }, 0 },
	{ "semtimedop", INT, 4, { INT, PTR, UINT, PTR }, 0 },
	{ "fadvise64", INT, 4, { INT, LONG, LONG, INT }, 0 },
	{ "timer_create", INT, 3, { INT, PTR, PTR }, 0 },
	{ "timer_settime", INT, 4, { INT, INT, PTR, PTR }, 0 },
	{ "timer_gettime", INT, 2, { INT, PTR }, 0 },
	{ "timer_getoverrun", INT, 1, { INT }, 0 },
	{ "timer_delete", INT, 1, { INT }, 0 },
	{ "clock_settime", INT, 2, { INT, PTR }, 0 },
	{ "clock_gettime", INT, 2, { INT, PTR }, 0 },
	{ "clock_getres", INT, 2, { INT, PTR }, 0 },
	{ "clock_nanosleep", INT, 4, { INT, INT, PTR, PTR }, 0 },
	{ "exit_group", VOID, 1, { INT }, 0 },
	{ "epoll_wait", INT, 4, { INT, PTR, INT, INT }, 0 },
	{ "epoll_ctl", INT, 4, { INT, INT, INT, PTR }, 0 },
	{ "tgkill", INT, 3, { INT, INT, INT }, 0 },
	{ "utimes", INT, 2, { STR, PTR }, 0 },
	{ "vserver", INT, 0, { VOID }, 0 },
	{ "mbind", INT, 6, { INT, UINT, INT, PTR, UINT, UINT }, 0 },
	{ "set_mempolicy", INT, 3, { INT, PTR, ULONG }, 0 },
	{ "get_mempolicy", INT, 5, { PTR, PTR, ULONG, ULONG, ULONG }, 0 },
	{ "mq_open", INT, 4, { STR, INT, INT, PTR }, 0 },
	{ "mq_unlink", INT, 1, { STR }, 0 },
	{ "mq_timedsend", INT, 5, { INT, STR, ULONG, UINT, PTR }, 0 },
	{ "mq_timedreceive", INT, 5, { INT, STR, UINT, PTR, PTR }, 0 },
	{ "mq_notify", INT, 2, { INT, PTR }, 0 },
	{ "mq_getsetattr", INT, 3, { INT, PTR, PTR }, 0 },
	{ "kexec_load", INT, 4, { ULONG, ULONG, PTR, ULONG }, 0 },
	{ "waitid", INT, 5, { INT, INT, PTR, INT, PTR }, 0 },
	{ "add_key", INT, 5, { STR, STR, PTR, ULONG, INT }, 0 },
	{ "request_key", INT, 4, { STR, STR, STR, INT }, 0 },
	{ "keyctl", INT, 5, { INT, INT, INT, INT, INT }, 0 },
	{ "ioprio_set", INT, 3, { INT, INT, INT }, 0 },
	{ "ioprio_get", INT, 2, { INT, INT }, 0 },
	{ "inotify_init", INT, 0, { VOID }, 0 },
	{ "inotify_add_watch", INT, 3, { INT, STR, UINT }, 0 },
	{ "inotify_rm_watch", INT, 2, { INT, INT }, 0 },
	{ "migrate_pages", LONG, 4, { INT, UINT, PTR, PTR }, 0 },
	{ "openat", INT, 4, { INT, STR, INT, INT }, 0 },
	{ "mkdirat", INT, 3, { INT, STR, INT }, 0 },
	{ "mknodat", INT, 4, { INT, STR, INT, INT }, 0 },
	{ "fchownat", INT, 5, { INT, STR, INT, INT, INT }, 0 },
	{ "futimesat", INT, 3, { INT, STR, PTR }, 0 },
	{ "newfstatat", INT, 4, { INT, STR, PTR, INT }, 0 },
	{ "unlinkat", INT, 3, { INT, STR, INT }, 0 },
	{ "renameat", INT, 4, { INT, STR, INT, STR }, 0 },
	{ "linkat", INT, 5, { INT, STR, INT, STR, INT }, 0 },
	{ "symlinkat", INT, 3, { STR, INT, STR }, 0 },
	{ "readlinkat", INT, 4, { INT, STR, STR, ULONG }, 0 },
	{ "fchmodat", INT, 3, { INT, STR, INT }, 0 },
	{ "faccessat", INT, 3, { INT, STR, INT }, 0 },
	{ "pselect6", INT, 6, { INT, PTR, PTR, PTR, PTR, PTR }, 0 },
	{ "ppoll", INT, 5, { PTR, INT, PTR, PTR, INT }, 0 },
	{ "unshare", INT, 1, { INT }, 0 },
	{ "set_robust_list", LONG, 2, { PTR, ULONG }, 0 },
	{ "get_robust_list", INT, 3, { INT, PTR, PTR }, 0 },
	{ "splice", LONG, 6, { INT, PTR, INT, PTR, ULONG, UINT }, 0 },
	{ "tee", LONG, 4, { INT, INT, ULONG, UINT }, 0 },
	{ "sync_file_range", INT, 4, { INT, ULONG, ULONG, UINT }, 0 },
	{ "vmsplice", INT, 4, { INT, PTR, ULONG, UINT }, 0 },
	{ "move_pages", LONG, 6, { ULONG, INT, PTR, PTR, PTR, INT }, 0 },
	{ "utimensat", INT, 4, { INT, STR, PTR, INT }, 0 },
	{ "epoll_pwait", INT, 6, { INT, PTR, INT, INT, PTR, INT }, 0 },
	{ "signalfd", INT, 3, { INT, PTR, INT }, 0 },
	{ "timerfd_create", INT, 2, { INT, INT }, 0 },
	{ "eventfd", INT, 2, { UINT, INT }, 0 },
	{ "fallocate", INT, 4, { INT, INT, LONG, LONG }, 0 },
	{ "timerfd_settime", INT, 4, { INT, INT, PTR, PTR }, 0 },
	{ "timerfd_gettime", INT, 2, { INT, PTR }, 0 },
	{ "accept4", INT, 4, { INT, PTR, PTR, INT }, 0 },
	{ "signalfd4", INT, 4, { INT, PTR, INT, INT }, 0 },
	{ "eventfd2", INT, 2, { INT, INT }, 0 },
	{ "epoll_create1", INT, 1, { INT }, 0 },
	{ "dup3", INT, 3, { INT, INT, INT }, 0 },
	{ "pipe2", INT, 2, { PTR, INT }, 0 },
	{ "inotify_init1", INT, 1, { INT }, 0 },
	{ "preadv", LONG, 5, { INT, PTR, INT, INT, LONG }, 0 },
	{ "pwritev", LONG, 5, { INT, PTR, INT, INT, INT }, 0 },
	{ "rt_tgsigqueueinfo", LONG, 4, { INT, INT, INT, PTR }, 0 },
	{ "perf_event_open", INT, 5, { PTR, INT, INT, INT, INT }, 0 },
	{ "recvmmsg", INT, 5, { INT, PTR, UINT, UINT, PTR }, 0 },
	{ "fanotify_init", INT, 2, { INT, INT }, 0 },
	{ "fanotify_mark", INT, 5, { INT, INT, INT, INT, STR }, 0 },
	{ "prlimit64", INT, 4, { INT, INT, PTR, PTR }, 0 },
	{ "name_to_handle_at", INT, 5, { INT, STR, PTR, PTR, INT }, 0 },
	{ "open_by_handle_at", INT, 3, { INT, PTR, INT }, 0 },
	{ "clock_adjtime", INT, 2, { INT, PTR }, 0 },
	{ "syncfs", INT, 1, { INT }, 0 },
	{ "sendmmsg", INT, 4, { INT, PTR, UINT, UINT }, 0 },
	{ "setns", INT, 2, { INT, INT }, 0 },
	{ "getcpu", INT, 3, { PTR, PTR, PTR }, 0 },
	{ "process_vm_readv", LONG, 6,
		{ INT, PTR, ULONG, PTR, ULONG, ULONG }, 0 },
	{ "process_vm_writev", LONG, 6,
		{ INT, PTR, ULONG, PTR, ULONG, ULONG }, 0 },
	{ "kcmp", INT, 5, { INT, INT, INT, ULONG, ULONG }, 0 },
	{ "finit_module", INT, 3, { INT, STR, INT }, 0 },
};

# define MAX_SYSCALL 314

#endif /* !SYSCALL_TAB_H_ */
